### PR TITLE
INamingConvention.AttributeName addition allowing customization of a configuration element's attribute naming.

### PR DESCRIPTION
**Pull request by pruiz**
Added a new AttributeName method to INamingConventions allowing finer control over configuration element's attributes, along with handling of Sys.ComponentModel.DefaultValueAttribute

### CODE REVIEW

**Comment by miensol** [comment]
Seems like a nice addition, thanks.

Will try to merge it soon.

**Comment by pruiz** [comment]
Sure, just let me know wether I can help somehow. ;)

**Comment by pruiz** [comment]
@miensol Hi, did you had a chance on reviewing this?

**Comment by pruiz** [comment]
Hi,

Oops, I missed that one.. I've commited a fix for this using legacy GetCustomAttribute(Type) instead, as upgrading the solution to another .net fx version seemed a task for an independent pull request.

Regards

**Comment by pruiz** [comment]
@miensol May I do anything else in order to get this merged? ;)

**Comment by pruiz** [comment]
Ok, this time I've ensured this builds on net3.5.. ;)

**Comment by miensol** [comment]
Thanks for the changes :+1: And sorry it took so long, it's been a while since I've used Windows :)

I've also pushed an update with version `1.2.0` to nuget.

**Pull request merged**
