### PR TITLE
Fix issues with [Required] validation when using standalone configuration files (configSource) on Mono

### PR DESCRIPTION
**Pull request by pruiz**
It looks like (on mono) when applying [Requred] attribute to a property within the root node of an standalone configuration file (ie. a file referenced by using the 'configSource' attribute), deserialization of such standalone configuration file would fail.

This pull-req fixes such (weird) issue by applying a workaround during deserialization on mono.

I've added a couple of unit tests reproducing the issue, which now pass succesfully during travis runs.

Regards

### CODE REVIEW

**Comment by pruiz** [comment]
@miensol Hi, did you had a chance at reviewing this?

**Comment by miensol** [comment]
Hi, this looks great, will merge it over the weekend, thanks.

**Comment by pruiz** [comment]
Hi @miensol,

Just let me know if I cal help, somehow.

**Comment by miensol** [comment]
@pruiz thanks again. Merged and released a patched version on Nuget.

**Pull request merged**
